# Generated by Django 5.2.17 on 2026-08-12 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PamSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('vendor', models.CharField(max_length=40)),
                ('base_url', models.URLField()),
                ('environment', models.CharField(default='production', max_length=40)),
                ('credential_reference', models.CharField(max_length=200)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('collection_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_successful_collection', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RuleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('severity_override', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=12)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('exempt_containers', models.JSONField(blank=True, default=list)),
                ('exempt_account_ids', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='ManagedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=256)),
                ('container', models.CharField(blank=True, max_length=256)),
                ('target_address', models.CharField(blank=True, max_length=256)),
                ('platform', models.CharField(blank=True, max_length=128)),
                ('kind', models.CharField(choices=[('human', 'Human administrator'), ('service', 'Service account'), ('bot', 'Robotic process account'), ('application', 'Application identity'), ('break_glass', 'Break glass'), ('vendor', 'Third party'), ('unknown', 'Unclassified')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('pending_delete', 'Pending deletion'), ('deleted', 'Deleted'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('owner_identity', models.CharField(blank=True, max_length=200)),
                ('owner_team', models.CharField(blank=True, max_length=200)),
                ('business_application', models.CharField(blank=True, max_length=200)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('last_rotation_at', models.DateTimeField(blank=True, null=True)),
                ('next_rotation_due', models.DateTimeField(blank=True, null=True)),
                ('rotation_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_rotation_enabled', models.BooleanField(blank=True, null=True)),
                ('last_verification_at', models.DateTimeField(blank=True, null=True)),
                ('verification_ok', models.BooleanField(blank=True, null=True)),
                ('last_rotation_failed', models.BooleanField(default=False)),
                ('rotation_failure_reason', models.CharField(blank=True, max_length=400)),
                ('consecutive_rotation_failures', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('exclusive_checkout', models.BooleanField(blank=True, null=True)),
                ('entitled_identity_count', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='inventory.pamsystem')),
            ],
            options={
                'ordering': ['system', 'container', 'username'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=12)),
                ('state', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('suppressed_until', models.DateTimeField(blank=True, null=True)),
                ('suppression_reason', models.TextField(blank=True)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('ticket_reference', models.CharField(blank=True, max_length=80)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inventory.managedaccount')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inventory.pamsystem')),
            ],
            options={
                'ordering': ['severity', '-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=16)),
                ('accounts_seen', models.PositiveIntegerField(default=0)),
                ('accounts_created', models.PositiveIntegerField(default=0)),
                ('accounts_updated', models.PositiveIntegerField(default=0)),
                ('accounts_retired', models.PositiveIntegerField(default=0)),
                ('activities_ingested', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='inventory.pamsystem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('onboarded', 'Onboarded'), ('rotated', 'Rotated'), ('rotation_failed', 'Rotation failed'), ('verification_failed', 'Verification failed'), ('ownership_changed', 'Ownership changed'), ('auto_rotation_disabled', 'Automatic rotation disabled'), ('auto_rotation_enabled', 'Automatic rotation enabled'), ('status_changed', 'Status changed'), ('retired', 'Removed from vault'), ('checked_out', 'Checked out'), ('checked_in', 'Checked in'), ('vendor_audit', 'Vendor audit event')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.CharField(blank=True, max_length=200)),
                ('source_address', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(blank=True, max_length=20)),
                ('ticket_reference', models.CharField(blank=True, max_length=80)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=300, unique=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.managedaccount')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['-occurred_at'], name='inventory_l_occurre_62f7a5_idx'), models.Index(fields=['kind', '-occurred_at'], name='inventory_l_kind_bf52cd_idx'), models.Index(fields=['exported_at'], name='inventory_l_exporte_144447_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=256)),
                ('target_address', models.CharField(max_length=256)),
                ('privilege_level', models.CharField(blank=True, max_length=80)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('onboarded', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('matched_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discoveries', to='inventory.managedaccount')),
            ],
            options={
                'ordering': ['target_address', 'username'],
                'unique_together': {('source', 'username', 'target_address')},
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20)),
                ('last_rotation_at', models.DateTimeField(blank=True, null=True)),
                ('auto_rotation_enabled', models.BooleanField(blank=True, null=True)),
                ('verification_ok', models.BooleanField(blank=True, null=True)),
                ('owner_identity', models.CharField(blank=True, max_length=200)),
                ('credential_age_days', models.IntegerField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.collectionrun')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.managedaccount')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['account', '-captured_at'], name='inventory_a_account_9f9f90_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='managedaccount',
            index=models.Index(fields=['kind', 'status'], name='inventory_m_kind_774ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='managedaccount',
            index=models.Index(fields=['next_rotation_due'], name='inventory_m_next_ro_88653d_idx'),
        ),
        migrations.AddIndex(
            model_name='managedaccount',
            index=models.Index(fields=['last_rotation_at'], name='inventory_m_last_ro_837466_idx'),
        ),
        migrations.AddIndex(
            model_name='managedaccount',
            index=models.Index(fields=['owner_identity'], name='inventory_m_owner_i_9c4655_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='managedaccount',
            unique_together={('system', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['state', 'severity'], name='inventory_f_state_6e5cec_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['rule_id', 'state'], name='inventory_f_rule_id_e275ab_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['exported_at'], name='inventory_f_exporte_7f5e3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='finding',
            unique_together={('rule_id', 'account', 'opened_at')},
        ),
        migrations.AddIndex(
            model_name='collectionrun',
            index=models.Index(fields=['system', '-started_at'], name='inventory_c_system__ae2278_idx'),
        ),
    ]
