# Generated by Django 5.2.17 on 2026-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pamsystem',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
