# Generated by Django 5.2.17 on 2026-08-12 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pamsystem_capabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('network_aaa', 'Network device accounting (TACACS+ or RADIUS)'), ('windows_auth', 'Windows security events'), ('unix_auth', 'Unix authentication and privilege escalation'), ('database_audit', 'Database audit'), ('cloud_trail', 'Cloud provider audit trail'), ('session_proxy', 'Privileged session proxy')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('ingest_reference', models.CharField(blank=True, max_length=300)),
                ('expected_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_ingest_at', models.DateTimeField(blank=True, null=True)),
                ('records_ingested', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=256)),
                ('asset_type', models.CharField(choices=[('network_device', 'Network device'), ('server', 'Server'), ('database', 'Database'), ('application', 'Application'), ('hypervisor', 'Hypervisor'), ('cloud_account', 'Cloud account'), ('directory', 'Directory'), ('unknown', 'Unclassified')], default='unknown', max_length=20)),
                ('environment', models.CharField(blank=True, max_length=40)),
                ('criticality', models.CharField(blank=True, max_length=20)),
                ('owner_team', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=120)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['identifier'],
                'indexes': [models.Index(fields=['asset_type'], name='inventory_t_asset_t_9d346b_idx'), models.Index(fields=['environment'], name='inventory_t_environ_93c0b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CredentialAssetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('unexplained_count', models.PositiveIntegerField(default=0)),
                ('mechanisms', models.JSONField(blank=True, default=list)),
                ('outside_mapped_scope', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='inventory.managedaccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='inventory.targetasset')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['account', '-last_seen_at'], name='inventory_c_account_4aebdf_idx')],
                'unique_together': {('account', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='UsageObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_account_name', models.CharField(max_length=256)),
                ('occurred_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mechanism', models.CharField(choices=[('brokered_session', 'Session brokered by the vault'), ('application_fetch', 'Credential provider fetch by an application'), ('target_authentication', 'Authentication seen on the target'), ('network_aaa', 'Network device accounting record')], max_length=24)),
                ('correlation', models.CharField(choices=[('brokered', 'Brokered by the vault, no correlation needed'), ('matched', 'Matched to a vault retrieval'), ('unexplained', 'No vault retrieval accounts for this login'), ('unmatched_account', 'Account is not managed in any vault'), ('pending', 'Not yet correlated')], default='pending', max_length=20)),
                ('correlation_lag_seconds', models.IntegerField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, max_length=200)),
                ('source_address', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(default='success', max_length=20)),
                ('session_reference', models.CharField(blank=True, max_length=120)),
                ('command_count', models.PositiveIntegerField(blank=True, null=True)),
                ('privilege_level', models.CharField(blank=True, max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=300, unique=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='inventory.managedaccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='inventory.targetasset')),
                ('correlated_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage', to='inventory.lifecycleevent')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='inventory.telemetrysource')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['-occurred_at'], name='inventory_u_occurre_758d80_idx'), models.Index(fields=['correlation', '-occurred_at'], name='inventory_u_correla_d39f44_idx'), models.Index(fields=['account', 'asset'], name='inventory_u_account_4ec47a_idx'), models.Index(fields=['mechanism'], name='inventory_u_mechani_c71538_idx'), models.Index(fields=['exported_at'], name='inventory_u_exporte_d6e017_idx')],
            },
        ),
    ]
