# Generated by Django 5.2.17 on 2026-08-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_telemetrysource_targetasset_credentialassetlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrysource',
            name='collector',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='telemetrysource',
            name='credential_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telemetrysource',
            name='cursor',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='telemetrysource',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
