# Generated by Django 5.2.17 on 2026-08-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_telemetrysource_collector_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='finding',
            name='subject_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='finding',
            unique_together={('rule_id', 'account', 'subject_key', 'opened_at')},
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['rule_id', 'subject_key'], name='inventory_f_rule_id_858503_idx'),
        ),
    ]
