# Generated by Django 5.2.17 on 2026-08-18 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_telemetrysource_collector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('scope', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('groups', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('independent', models.BooleanField(default=False)),
                ('team', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('principal_type', models.CharField(choices=[('developer', 'Developer'), ('engineer', 'Engineer'), ('bot', 'Bot or automation identity'), ('service', 'Service identity'), ('vendor', 'Third party'), ('unknown', 'Unclassified')], default='unknown', max_length=16)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('team', models.CharField(blank=True, max_length=120)),
                ('responsible_owner', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('managed_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principals', to='inventory.managedaccount')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('github_enterprise', 'GitHub Enterprise'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('azure_devops', 'Azure DevOps'), ('artifact_registry', 'Artifact registry'), ('ci_pipeline', 'Continuous integration pipeline'), ('cloud_account', 'Cloud account'), ('network_group', 'Network device group'), ('database', 'Database'), ('other', 'Other')], max_length=24)),
                ('identifier', models.CharField(max_length=300)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('criticality', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], default='moderate', max_length=12)),
                ('production', models.BooleanField(default=False)),
                ('data_classification', models.CharField(blank=True, max_length=40)),
                ('owner_identity', models.CharField(blank=True, max_length=200)),
                ('owner_team', models.CharField(blank=True, max_length=120)),
                ('business_application', models.CharField(blank=True, max_length=200)),
                ('archived', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['platform', 'identifier'],
                'indexes': [models.Index(fields=['platform', 'production'], name='access_reso_platfor_87130c_idx'), models.Index(fields=['criticality'], name='access_reso_critica_2c6c67_idx')],
                'unique_together': {('platform', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('platform', models.CharField(blank=True, choices=[('github', 'GitHub'), ('github_enterprise', 'GitHub Enterprise'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('azure_devops', 'Azure DevOps'), ('artifact_registry', 'Artifact registry'), ('ci_pipeline', 'Continuous integration pipeline'), ('cloud_account', 'Cloud account'), ('network_group', 'Network device group'), ('database', 'Database'), ('other', 'Other')], max_length=24)),
                ('applies_to_production_only', models.BooleanField(default=False)),
                ('minimum_criticality', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=12)),
                ('access_levels', models.JSONField(blank=True, default=list)),
                ('principal_types', models.JSONField(blank=True, default=list)),
                ('approvals_required', models.PositiveSmallIntegerField(default=1)),
                ('approver_groups', models.JSONField(blank=True, default=list)),
                ('require_resource_owner', models.BooleanField(default=False)),
                ('require_ticket_reference', models.BooleanField(default=True)),
                ('require_justification', models.BooleanField(default=True)),
                ('maximum_duration_days', models.PositiveIntegerField(default=30)),
                ('standing_access_allowed', models.BooleanField(default=False)),
                ('require_owner_for_bots', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='access.resource')),
            ],
            options={
                'verbose_name_plural': 'approval policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('access_level', models.CharField(choices=[('read', 'Read'), ('triage', 'Triage'), ('write', 'Write'), ('maintain', 'Maintain'), ('admin', 'Administer'), ('deploy', 'Deploy to production')], max_length=12)),
                ('requested_by', models.CharField(max_length=200)),
                ('justification', models.TextField(blank=True)),
                ('ticket_reference', models.CharField(blank=True, max_length=80)),
                ('requested_days', models.PositiveIntegerField(blank=True, null=True)),
                ('approvals_required', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved, awaiting provisioning'), ('provisioned', 'Provisioned'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('handoff_reference', models.CharField(blank=True, max_length=120)),
                ('handoff_system', models.CharField(blank=True, max_length=80)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='access.approvalpolicy')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='access.principal')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='access.resource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'Read'), ('triage', 'Triage'), ('write', 'Write'), ('maintain', 'Maintain'), ('admin', 'Administer'), ('deploy', 'Deploy to production')], max_length=12)),
                ('origin', models.CharField(choices=[('approved', 'From an approved request'), ('discovered', 'Found on the platform, no request behind it'), ('imported', 'Imported at onboarding'), ('break_glass', 'Emergency, approved after the fact')], default='discovered', max_length=16)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('absent_since', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='access.accessrequest')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='access.principal')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='access.resource')),
            ],
            options={
                'ordering': ['resource', 'principal'],
            },
        ),
        migrations.CreateModel(
            name='AccessReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_identity', models.CharField(blank=True, max_length=200)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('retain', 'Retain'), ('revoke', 'Revoke'), ('modify', 'Reduce')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='access.accessgrant')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='access.accessreview')),
            ],
            options={
                'ordering': ['review', 'grant'],
                'unique_together': {('review', 'grant')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('approver_identity', models.CharField(max_length=200)),
                ('approver_groups', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('abstained', 'Abstained')], max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_address', models.CharField(blank=True, max_length=64)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='access.accessrequest')),
            ],
            options={
                'ordering': ['request', 'sequence'],
                'unique_together': {('request', 'sequence')},
            },
        ),
        migrations.AddIndex(
            model_name='principal',
            index=models.Index(fields=['principal_type', 'active'], name='access_prin_princip_743a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['state', '-created_at'], name='access_acce_state_a5a9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['expires_at'], name='access_acce_expires_fb7bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['origin'], name='access_acce_origin_35c741_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['expires_at'], name='access_acce_expires_b7f336_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['revoked_at'], name='access_acce_revoked_f8b826_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accessgrant',
            unique_together={('principal', 'resource', 'access_level')},
        ),
    ]
